### ISSUE TITLE
KeyError when generating CDs collaborative indexing method dataset

### ISSUE THREAD

**Issue by liyang2019** [agiresearch/OpenP5#27]
Hi,

I got the following error when generating the CDs collaborative indexing method dataset using
```
sh generate_dataset_1.sh 
```

Error:
Traceback (most recent call last):
  File "/usr/local/google/home/lyliyang/OpenP5/./src/src_llama/generate_dataset.py", line 133, in <module>
    main(args)
  File "/usr/local/google/home/lyliyang/OpenP5/./src/src_llama/generate_dataset.py", line 36, in main
    reindex_user_seq_dict, item_map = indexing.collaborative_indexing(args.data_path, args.dataset, user_sequence_dict, \
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/lyliyang/OpenP5/src/src_llama/utils/indexing.py", line 145, in collaborative_indexing
    reindex_user_sequence_dict = reindex(user_sequence_dict, user_map, item_map)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/google/home/lyliyang/OpenP5/src/src_llama/utils/indexing.py", line 319, in reindex
    reindex_user_sequence_dict[uid] = [item_map[i] for i in items]

**Comment by shuyuan-x** [comment]
Hello, could you provide more details? I tried running the code with provided data but didn't encounter the same error.
<img width="588" alt="image" src="https://github.com/agiresearch/OpenP5/assets/47437688/baeae89f-f4a5-4ee2-88cb-bffae29c443f">

**Comment by liyang2019** [comment]
It looks like it maybe due to some data corruption issue, I re-downloaded the CDs data, and now there is no error now.

Thanks!
